version: '2'
services:
    dental-app:
        image: dental
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://dental-postgresql:5432/Dental
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    dental-postgresql:
        extends:
            file: postgresql.yml
            service: dental-postgresql
