version: '2'
services:
    dental-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/Dental/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=Dental
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
